/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteRouteImport } from './routes/$game/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIndexRouteImport } from './routes/$game/index'
import { Route as GameIdRouteRouteImport } from './routes/$game/$id/route'
import { Route as GameIdIndexRouteImport } from './routes/$game/$id/index'
import { Route as GameIdTokenIndexRouteImport } from './routes/$game/$id/$token/index'

const GameRouteRoute = GameRouteRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameIdRouteRoute = GameIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameIdIndexRoute = GameIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameIdRouteRoute,
} as any)
const GameIdTokenIndexRoute = GameIdTokenIndexRouteImport.update({
  id: '/$token/',
  path: '/$token/',
  getParentRoute: () => GameIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$game': typeof GameRouteRouteWithChildren
  '/$game/$id': typeof GameIdRouteRouteWithChildren
  '/$game/': typeof GameIndexRoute
  '/$game/$id/': typeof GameIdIndexRoute
  '/$game/$id/$token/': typeof GameIdTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$game': typeof GameIndexRoute
  '/$game/$id': typeof GameIdIndexRoute
  '/$game/$id/$token': typeof GameIdTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$game': typeof GameRouteRouteWithChildren
  '/$game/$id': typeof GameIdRouteRouteWithChildren
  '/$game/': typeof GameIndexRoute
  '/$game/$id/': typeof GameIdIndexRoute
  '/$game/$id/$token/': typeof GameIdTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$game'
    | '/$game/$id'
    | '/$game/'
    | '/$game/$id/'
    | '/$game/$id/$token/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$game' | '/$game/$id' | '/$game/$id/$token'
  id:
    | '__root__'
    | '/'
    | '/$game'
    | '/$game/$id'
    | '/$game/'
    | '/$game/$id/'
    | '/$game/$id/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRouteRoute: typeof GameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$game': {
      id: '/$game'
      path: '/$game'
      fullPath: '/$game'
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/': {
      id: '/$game/'
      path: '/'
      fullPath: '/$game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/$game/$id': {
      id: '/$game/$id'
      path: '/$id'
      fullPath: '/$game/$id'
      preLoaderRoute: typeof GameIdRouteRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/$game/$id/': {
      id: '/$game/$id/'
      path: '/'
      fullPath: '/$game/$id/'
      preLoaderRoute: typeof GameIdIndexRouteImport
      parentRoute: typeof GameIdRouteRoute
    }
    '/$game/$id/$token/': {
      id: '/$game/$id/$token/'
      path: '/$token'
      fullPath: '/$game/$id/$token/'
      preLoaderRoute: typeof GameIdTokenIndexRouteImport
      parentRoute: typeof GameIdRouteRoute
    }
  }
}

interface GameIdRouteRouteChildren {
  GameIdIndexRoute: typeof GameIdIndexRoute
  GameIdTokenIndexRoute: typeof GameIdTokenIndexRoute
}

const GameIdRouteRouteChildren: GameIdRouteRouteChildren = {
  GameIdIndexRoute: GameIdIndexRoute,
  GameIdTokenIndexRoute: GameIdTokenIndexRoute,
}

const GameIdRouteRouteWithChildren = GameIdRouteRoute._addFileChildren(
  GameIdRouteRouteChildren,
)

interface GameRouteRouteChildren {
  GameIdRouteRoute: typeof GameIdRouteRouteWithChildren
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteRouteChildren: GameRouteRouteChildren = {
  GameIdRouteRoute: GameIdRouteRouteWithChildren,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteRouteWithChildren = GameRouteRoute._addFileChildren(
  GameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRouteRoute: GameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
