/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameLayoutRouteImport } from './routes/$game/_layout'
import { Route as GameLayoutIndexRouteImport } from './routes/$game/_layout/index'
import { Route as GameLayoutIdLayoutRouteImport } from './routes/$game/_layout/$id/_layout'
import { Route as GameLayoutIdLayoutIndexRouteImport } from './routes/$game/_layout/$id/_layout/index'
import { Route as GameLayoutIdLayoutTokenIndexRouteImport } from './routes/$game/_layout/$id/_layout/$token/index'

const GameRouteImport = createFileRoute('/$game')()
const GameLayoutIdRouteImport = createFileRoute('/$game/_layout/$id')()

const GameRoute = GameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLayoutRoute = GameLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => GameRoute,
} as any)
const GameLayoutIdRoute = GameLayoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameLayoutRoute,
} as any)
const GameLayoutIndexRoute = GameLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameLayoutRoute,
} as any)
const GameLayoutIdLayoutRoute = GameLayoutIdLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => GameLayoutIdRoute,
} as any)
const GameLayoutIdLayoutIndexRoute = GameLayoutIdLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameLayoutIdLayoutRoute,
} as any)
const GameLayoutIdLayoutTokenIndexRoute =
  GameLayoutIdLayoutTokenIndexRouteImport.update({
    id: '/$token/',
    path: '/$token/',
    getParentRoute: () => GameLayoutIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$game': typeof GameLayoutRouteWithChildren
  '/$game/': typeof GameLayoutIndexRoute
  '/$game/$id': typeof GameLayoutIdLayoutRouteWithChildren
  '/$game/$id/': typeof GameLayoutIdLayoutIndexRoute
  '/$game/$id/$token': typeof GameLayoutIdLayoutTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$game': typeof GameLayoutIndexRoute
  '/$game/$id': typeof GameLayoutIdLayoutIndexRoute
  '/$game/$id/$token': typeof GameLayoutIdLayoutTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$game': typeof GameRouteWithChildren
  '/$game/_layout': typeof GameLayoutRouteWithChildren
  '/$game/_layout/': typeof GameLayoutIndexRoute
  '/$game/_layout/$id': typeof GameLayoutIdRouteWithChildren
  '/$game/_layout/$id/_layout': typeof GameLayoutIdLayoutRouteWithChildren
  '/$game/_layout/$id/_layout/': typeof GameLayoutIdLayoutIndexRoute
  '/$game/_layout/$id/_layout/$token/': typeof GameLayoutIdLayoutTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$game'
    | '/$game/'
    | '/$game/$id'
    | '/$game/$id/'
    | '/$game/$id/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$game' | '/$game/$id' | '/$game/$id/$token'
  id:
    | '__root__'
    | '/'
    | '/$game'
    | '/$game/_layout'
    | '/$game/_layout/'
    | '/$game/_layout/$id'
    | '/$game/_layout/$id/_layout'
    | '/$game/_layout/$id/_layout/'
    | '/$game/_layout/$id/_layout/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$game': {
      id: '/$game'
      path: '/$game'
      fullPath: '/$game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/_layout': {
      id: '/$game/_layout'
      path: '/$game'
      fullPath: '/$game'
      preLoaderRoute: typeof GameLayoutRouteImport
      parentRoute: typeof GameRoute
    }
    '/$game/_layout/$id': {
      id: '/$game/_layout/$id'
      path: '/$id'
      fullPath: '/$game/$id'
      preLoaderRoute: typeof GameLayoutIdRouteImport
      parentRoute: typeof GameLayoutRoute
    }
    '/$game/_layout/': {
      id: '/$game/_layout/'
      path: '/'
      fullPath: '/$game/'
      preLoaderRoute: typeof GameLayoutIndexRouteImport
      parentRoute: typeof GameLayoutRoute
    }
    '/$game/_layout/$id/_layout': {
      id: '/$game/_layout/$id/_layout'
      path: '/$id'
      fullPath: '/$game/$id'
      preLoaderRoute: typeof GameLayoutIdLayoutRouteImport
      parentRoute: typeof GameLayoutIdRoute
    }
    '/$game/_layout/$id/_layout/': {
      id: '/$game/_layout/$id/_layout/'
      path: '/'
      fullPath: '/$game/$id/'
      preLoaderRoute: typeof GameLayoutIdLayoutIndexRouteImport
      parentRoute: typeof GameLayoutIdLayoutRoute
    }
    '/$game/_layout/$id/_layout/$token/': {
      id: '/$game/_layout/$id/_layout/$token/'
      path: '/$token'
      fullPath: '/$game/$id/$token'
      preLoaderRoute: typeof GameLayoutIdLayoutTokenIndexRouteImport
      parentRoute: typeof GameLayoutIdLayoutRoute
    }
  }
}

interface GameLayoutIdLayoutRouteChildren {
  GameLayoutIdLayoutIndexRoute: typeof GameLayoutIdLayoutIndexRoute
  GameLayoutIdLayoutTokenIndexRoute: typeof GameLayoutIdLayoutTokenIndexRoute
}

const GameLayoutIdLayoutRouteChildren: GameLayoutIdLayoutRouteChildren = {
  GameLayoutIdLayoutIndexRoute: GameLayoutIdLayoutIndexRoute,
  GameLayoutIdLayoutTokenIndexRoute: GameLayoutIdLayoutTokenIndexRoute,
}

const GameLayoutIdLayoutRouteWithChildren =
  GameLayoutIdLayoutRoute._addFileChildren(GameLayoutIdLayoutRouteChildren)

interface GameLayoutIdRouteChildren {
  GameLayoutIdLayoutRoute: typeof GameLayoutIdLayoutRouteWithChildren
}

const GameLayoutIdRouteChildren: GameLayoutIdRouteChildren = {
  GameLayoutIdLayoutRoute: GameLayoutIdLayoutRouteWithChildren,
}

const GameLayoutIdRouteWithChildren = GameLayoutIdRoute._addFileChildren(
  GameLayoutIdRouteChildren,
)

interface GameLayoutRouteChildren {
  GameLayoutIndexRoute: typeof GameLayoutIndexRoute
  GameLayoutIdRoute: typeof GameLayoutIdRouteWithChildren
}

const GameLayoutRouteChildren: GameLayoutRouteChildren = {
  GameLayoutIndexRoute: GameLayoutIndexRoute,
  GameLayoutIdRoute: GameLayoutIdRouteWithChildren,
}

const GameLayoutRouteWithChildren = GameLayoutRoute._addFileChildren(
  GameLayoutRouteChildren,
)

interface GameRouteChildren {
  GameLayoutRoute: typeof GameLayoutRouteWithChildren
}

const GameRouteChildren: GameRouteChildren = {
  GameLayoutRoute: GameLayoutRouteWithChildren,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
